#!/bin/bash
# 指令集


case `uname` in
    *CYGWIN*) local cmdPlatform="Cygwin" ;;
    *) local cmdPlatform="Linux" ;;
esac


## 系統環境變數

local ys="${HOME}/ys"
local ys_nodeApp="$ys/capp/nodeApp/node_modules"

case $cmdPlatform in
    "Cygwin")
        # 不明白 /cygdrive/c/ 與 C:/ 的差異
        # 但是 node 好像呼叫決對路徑會冠上 C:/

        local ProgramFile86="/cygdrive/c/Program Files (x86)"
        local UserProFile="/cygdrive/c/Users/bwaycer"
        export Cer="/cygdrive/c/Cer"
        ;;
    "Linux")
        export Cer="/mnt/hgfs/Cer"
        ;;
esac


## 應用程式

case $cmdPlatform in
    "Cygwin")
        if ! type su >/dev/null 2>&1; then
            echo -e "\e[33m請執行 \`~/ys/myBash/cygwin_su_sh_usrLocalBinInit_userName\` 以取得常用檔案\e[0m"
        fi

        alias open="cygstart" # explorer.exe 由微軟開發
        alias node.gitbook="node \"$(cygpath.exe -w $ys_nodeApp/gitbook-cli/bin/gitbook.js)\""
        ;;
    "Linux")
        alias open="xdg-open"
        alias node.gitbook="$ys_nodeApp/.bin/gitbook"
        ;;
esac


## 移動指令

alias Bway.cd.Cer="cd $Cer"

case $cmdPlatform in
    "Cygwin")
        alias Bway.cd.ProgramFile86="cd $ProgramFile86"
        alias Bway.cd.User="cd $UserProFile"
        alias Bway.cd.Desktop="cd $UserProFile/Desktop"
        alias Bway.cd.Download="cd $UserProFile/Downloads"
        ;;
    "Linux")
        ;;
esac


## 連線

alias Bway.link.ptt="ssh bbsu@ptt.cc"

