#!/bin/bash
# 記事簿


## 時間戳 timestamp

echo `date "+%Y-%m-%d %A %H:%M:%S"`


## 字條

BwayNote(){
    local target="${HOME}/ys/notepad.txt"

    while read line
    do
        if [ "$line" ]; then
            echo "    $line"
        fi
    done < $target
}

BwayNote

