#!/bin/bash
# 命令行基礎設定


## 外觀介面


##### 編碼

export LESSCHARSET=utf-8


##### 顯示顏色

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 &> /dev/null; then
        # We have color support; assume it's compliant with Ecma-48
        # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
        # a case would tend to support setf rather than setaf.)
        color_prompt=yes
    else
        color_prompt=
    fi
fi


##### 依顏色改變訊息列樣式

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]: \[\033[01;36m\]\w\[\033[00m\] \n\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h: \w \n\$ '
fi
unset color_prompt force_color_prompt



## 自訂環境變數


# alias 寫法：
# alias a=string b=string # 以 "空白" 間隔參數


##### 基礎操做

alias ls='ls -hF'
alias la='ls -A'                        # 顯示不含 ./ ../ 的其他全部檔案清單
alias ll='ls -al'                       # 顯示全部檔案清單
alias lc='ll --color=tty'               # 以顏色區分文件類型


##### 過濾字串

alias grep='grep --color=auto'          # 塗上顏色

