#!/bin/bash
# 船塢工人 - 單次執行


##shStyle ###


source shbase.redirection.sh
source shbase "#abase"


##shStyle ###


shScript_route() { return; }


##shStyle 共享變數


dockershPath="$_dirsh/_dockersh"
dockershVolumePath="/dockersh"
bwaycerVolumePath="/home/bwaycer"
onceTmpVolumePath="/home/onceTmp"

onceRunVolumePath="$dockershVolumePath/onceRun.sh"


##shStyle 介面函式


showHelpRecord "main" "\
船塢工人 - 單次執行
[[USAGE]] <命令參數 ...>
[[OPT]]
      --image <映像文件名稱>   建立環境的映像文件。
      --user1000               以 \`--user 1000:1000\` 建立環境。
      --myhome                 以 \`--volume \$HOME:$bwaycerVolumePath\` 建立環境。
      --dock                   掛載 \"/var/run/docker.sock\" 以啟用容器內的 docker 命令。
  -h, --help                   幫助。
"
fnOpt_main() {
    case "$1" in
        --image )
            [ -z "$2" ] && return 4

            opt_image=$2
            return 2
            ;;
        --user1000 )
            opt_user1000=1
            return 1
            ;;
        --myhome )
            opt_myhome=1
            return 1
            ;;
        --dock )
            opt_dock=1
            return 1
            ;;
        -h | --help ) showHelp "$_fileName" ;;
        * )
            if [ -z "$2" ]; then
                opt_carryOpt[${#opt_carryOpt[@]}]=$1
                return 1
            else
                opt_carryOpt[${#opt_carryOpt[@]}]=$1
                opt_carryOpt[${#opt_carryOpt[@]}]=$2
                return 2
            fi
            ;;
    esac
}
fnSh_main() {
    opt_image=""
    opt_user1000=0
    opt_myhome=0
    opt_dock=0
    opt_carryOpt=()
    parseOption "$_fileName"

    if [ -z "$opt_image" ]; then
        echo "未提供 \`--image\` 映像文件名稱。" \
            | loxog -f "$_fileName" --stderr err
        exit 1
    fi

    local key
    local dvPath=() # defaultVolumePath=()
    local dockerCmdList=("docker" "run" "--rm" "-it")

    dvPath+=("$dockershPath:$dockershVolumePath")

    if [ $opt_user1000 -eq 1 ]; then
        dockerCmdList+=("--user" "1000:1000")
    fi

    if [ $opt_myhome -eq 1 ]; then
        dvPath+=("$HOME:$bwaycerVolumePath")
    else
        dvPath+=("$_PWD:$onceTmpVolumePath")
    fi

    if [ $opt_dock -eq 1 ]; then
        dockerCmdList+=("--volume" "/var/run/docker.sock:/var/run/docker.sock")
    fi

    for key in "${dvPath[@]}"
    do
        dockerCmdList+=("--volume" "$key")
    done

    for key in "${opt_carryOpt[@]}"
    do
        dockerCmdList+=("$key")
    done

    dockerCmdList+=("$opt_image")

    dockerCmdList+=("$onceRunVolumePath")

    if [ $opt_myhome -eq 1 ]; then
        dockerCmdList+=("--cd" "$_PWD")
    else
        dockerCmdList+=("--cd" "$onceTmpVolumePath")
    fi

    for key in "${_args[@]}"
    do
        dockerCmdList+=("$key")
    done

    echo "\$ ${dockerCmdList[@]}<ENTER>"
    exec "${dockerCmdList[@]}"
}


##shStyle 函式庫



##shStyle ###


shScript "main" "$@"

