#!/bin/bash
# 狗語言 - 交叉編譯

# https://baike.baidu.com/item/交叉编译
# https://blog.csdn.net/panshiqu/article/details/53788067


##shStyle ###


source shbase.redirection.sh
source shbase "#abase"


##shStyle ###


shScript_route() { return; }


##shStyle 共享變數



##shStyle 介面函式


showHelpRecord "main" "\
狗語言 - 交叉編譯
[[USAGE]] <編譯文件路徑>
[[OPT]]
      --os <環境>     設定環境。
      --arch <環境>   設定環境。
  -i, --install       使用 \`go install\`。
  -b, --build         使用 \`go build\`。
  -h, --help          幫助。
"
fnOpt_main() {
    case "$1" in
        --os )
            [ -z "$2" ] && return 4

            opt_os=$2
            return 2
            ;;
        --arch )
            [ -z "$2" ] && return 4

            opt_arch=$2
            return 2
            ;;
        -i | --install )
            opt_buildMethod="install"
            return 1
            ;;
        -b | --build )
            opt_buildMethod="build"
            return 1
            ;;
        -h | --help ) showHelp "$_fileName" ;;
        * )
            if [ -z "$2" ]; then
                opt_carryOpt+=($1)
                return 1
            else
                opt_carryOpt+=($1)
                opt_carryOpt+=($2)
                return 2
            fi
            ;;
    esac
}
fnSh_main() {
    opt_os=""
    opt_arch=""
    opt_buildMethod="build"
    opt_carryOpt=()
    parseOption "$_fileName"

    local compilerFilePath="${_args[0]}"

    local key
    local cmdMsg=""
    local goCmdList=("go")

    if [ -n "$opt_os" ]; then
        cmdMsg+="export GOOS=$opt_os; "
    fi

    if [ -n "$opt_arch" ]; then
        cmdMsg+="export GOARCH=$opt_arch; "
    fi

    if [ "$opt_buildMethod" == "install" ]; then
        goCmdList+=("install")
    else
        goCmdList+=("build")
    fi

    for key in "${opt_carryOpt[@]}"
    do
        goCmdList+=("$key")
    done

    goCmdList+=("$compilerFilePath")

    echo "\$ $cmdMsg ${goCmdList[@]}<ENTER>"

    if [ -n "$opt_os" ]; then
        export GOOS=$opt_os;
    fi
    if [ -n "$opt_arch" ]; then
        export GOARCH=$opt_arch;
    fi
    exec "${goCmdList[@]}"
}


##shStyle 函式庫



##shStyle ###


shScript "main" "$@"

