#!/bin/bash
# 增量備份

# [[USAGE]] <被備份的目錄路徑> <儲存備份的目錄路徑>
# [[OPT]]
#       --upzip                還原備份資料。
#       --exclude <文件路徑>   排除文件路徑指定的文件或目錄。
#   -h, --help                 幫助。


##shStyle 共享變數



##shStyle 介面函式


fnMain() {
    local opt_unzip=0
    local opt_excludeCmdListPart=()

    while [ -n "y" ]
    do
        case "$1" in
            --unzip )
                opt_unzip=1
                shift
                ;;
            --exclude )
                [ -z "$2" ] && fnThrow_optRtn4 "$1"

                opt_excludeCmdListPart=("--exclude" "$2")
                shift 2
                ;;
            -h | --help ) sed -n "2,9p" "$__filename" && exit ;;
            * ) break ;;
        esac
    done

    local backupDirPath="$1"
    local storeDirPath="$2"

    local listedIncrementalFile tarFile
    if [ $opt_unzip -eq 0 ]; then
        [ -d "$backupDirPath" ] || fnThrow "找不到 \"$backupDirPath\" 被備份的目錄。"
        [ -d "$storeDirPath"  ] || mkdir -p "$storeDirPath"

        tarFilePath="$storeDirPath/`date -u +"%Y-%m-%dZ-%s%3Nms"`.tar.xz"
        incrementalFilePath="$storeDirPath/incrementalRecord"

        set -x
        tar -Jpvc -f "$tarFilePath" "${opt_excludeCmdListPart[@]}" \
            --listed-incremental "$incrementalFilePath" \
            --one-file-system \
            -C "$backupDirPath" .
    else
        [ -d "$backupDirPath" ] || mkdir -p "$backupDirPath"
        [ -d "$storeDirPath"  ] || fnThrow "找不到 \"$storeDirPath\" 儲存備份的目錄。"

        set -x
        for backupFile in `ls "$storeDirPath"/*.tar.xz`
        do
            tar -Jvx -f "$backupFile" --incremental --no-same-owner -C "$backupDirPath"
        done
    fi
}


##shStyle 函式庫


fnLog() {
    local msg="$1"
    local formatArgus="[$_fileName]: %s$_br"
    printf "$formatArgus" "$msg"
}
fnThrow() {
    local msg="$1"
    fnLog "$msg" >&2
    exit 1
}
fnThrow_optRtn4() {
    local opt="$1"
    fnThrow "不符合 \"$opt\" 選項的預期值。"
}


##shStyle ###


_br="
"

__filename=`realpath "$0"`
_fileName=`basename "$__filename"`


fnMain "$@"

