#!/bin/bash
# 網址編碼


#---
# 來源： https://gist.github.com/cdown/1163649
#---


# fnUrlencode <URL>
fnUrlencode() {
    local _stdin=`[ ! -t 0 ] && while read pipeData; do echo $pipeData; done <&0`
    local url="$1"

    [ -n "$_stdin" ] && url=$_stdin

    if [ "$url" ]; then
        old_lc_collate=$LC_COLLATE
        LC_COLLATE=C

        length="${#url}"
        for (( i = 0; i < length; i++ )); do
            c="${url:i:1}"
            case $c in
                [a-zA-Z0-9.~_-] ) printf "$c" ;;
                * ) printf '%%%02X' "'$c" ;;
            esac
        done
        echo

        LC_COLLATE=$old_lc_collate
    fi
}

fnUrlencode "$@"

