#!/bin/bash
# 執行環境建立文件


##shStyle ###


source shbase "#loxog"


##shStyle 共享變數


_br="
"

ysPath=""
plantHome=""
envCode=-1


##shStyle 介面函式


fnYsBash_build() {
    local _fileName="$1"
    local ysPathArge="$2"
    local plantHomeArge="$3"
    local envCodeArge=$4
    local ysBashBuildPath="$5"
    local onlyLine="$6"

    if [ ! -f "$ysBashBuildPath" ]; then
        loxog -f "$_fileName" war \
            "環境樹未被建立，請執行 \`$_fileName plant --build\`。"
        exit 1
    fi

    if [ -z "`cat "$ysBashBuildPath"`" ]; then
        exit
    fi

    ysPath=$ysPathArge
    plantHome="$plantHomeArge"
    envCode=$envCodeArge

    echo
    echo "=============================="
    echo "===    執行環境安裝文件    ==="
    echo "=============================="
    echo

    local line filePath readFilePath
    local lineIdx=0
    while read line
    do
        ((lineIdx++))
        [ -n "$line" ] && [ "${line::1}" != "#" ] || continue
        [ -n "$onlyLine" ] && [ -z "`grep -Fo ",$lineIdx," <<< ",$onlyLine,"`" ] \
            && continue || echo -n

        fnReplaceHome "$line"
        filePath="$rtnReplaceHome"

        echo "$_br$_br=== $filePath ===$_br"

        # 文件路徑資訊
        __filename=`realpath "$filePath"`
        _dirsh=`dirname "$__filename"`
        _fileName=`basename "$__filename"`

        # 於執行文件中可使用外層既有的變數 (類似 source)
        # 但文件中設定的變數不會影響外層變數
        echo "$filePath" |
            while read readFilePath; do source "$readFilePath" "$readFilePath"; done
    done <<< "`cat "$ysBashBuildPath"`"
}


##shStyle 函式庫


rtnReplaceHome=""
fnReplaceHome() {
    local filePathArgu="$1"

    local filePath
    local originTxt='$HOME/'

    if [ "${filePathArgu::${#originTxt}}" == "${originTxt}" ]; then
        filePath="$HOME/${filePathArgu:${#originTxt}}"
    else
        filePath="$filePathArgu"
    fi

    rtnReplaceHome=$filePath
}


##shStyle ###


fnYsBash_build "$@"

