#!/bin/bash
# Ys 命令環境


##shStyle ###


source shbase.redirection.sh
source shbase "#abase"
source shbase "pathRelative.lib.sh"


##shStyle ###


shScript_route() {
    case "$1" in
    note ) _shCmdLevel=1 ;;
    edit ) _shCmdLevel=1 ;;
    esac
}


##shStyle 介面函式


showHelpRecord "main" "\
環境樹設置
[[USAGE]]
[[SUBCMD]]
  note   [[BRIEFLY:note]]
  edit   [[BRIEFLY:edit]]
[[OPT]]
  -h, --help   幫助。
"
# fnOpt_main() {}
fnSh_main() {
    showHelp "$_fileName"
}

showHelpRecord "main_note" "\
顯示記事字條。
# 使用 \`ysBash edit note\` 創建編輯。
[[USAGE]]
[[OPT]]
  -h, --help   幫助。
"
fnOpt_main_note() {
    case "$1" in
        -h | --help ) showHelp "$_fileName" ;;
        * ) return 3 ;;
    esac
}
fnSh_main_note() {
    parseOption "$_fileName"

    $_dirsh/ysBash_note "$notePath" \
        "(用 \`$_fileName edit note\` 記事吧！)"
}

showHelpRecord "main_edit" "\
編輯相關文件。
# note： 筆記
[[USAGE]] [文件 ... (note)]
[[OPT]]
  -h, --help   幫助。
"
fnOpt_main_edit() {
    case "$1" in
        -h | --help ) showHelp "$_fileName" ;;
        * ) return 3 ;;
    esac
}
fnSh_main_edit() {
    parseOption "$_fileName"

    local item openNameList filePath templateFilePath
    local isNotFined=0
    local openFileList=()

    if [ ${#_args[@]} -eq 0 ]; then
        openNameList=(note)
    else
        openNameList=("${_args[@]}")
    fi

    for item in "${openNameList[@]}"
    do
        case $item in
            note )
                templateFilePath="$_dirsh/_${noteFileName}.template"
                filePath=$notePath
                [ ! -f "$filePath" ] && cp "$templateFilePath" "$filePath"
                openFileList[${#openFileList[@]}]=$filePath
                ;;
            * )
                isNotFined=1
                loxog -f "$_fileName" --stderr err "找不到 \"$item\" 文件。"
                ;;
        esac
    done

    [ $isNotFined -eq 1 ] && exit 1

    vim "${openFileList[@]}"
}


##shStyle 共享變數


ysPath=`sed -n 1p "$_dirsh/_ysPath.config"`
ysPath_capp="$ysPath/capp"

noteFileName="notepad.txt"
notePath="$ysPath_capp/ysBash.$noteFileName"


##shStyle 函式庫



##shStyle ###


shScript "main" "$@"

