#!/bin/bash


fnYsBash_installDefaultApp() {
    local tmp tmpB


    ## vim-plug
    if [ -n "`echo " 1 2 " | grep " $cmdPlatformCode "`" ]; then
        tmp="$ysUserdirPath/.vim/autoload"
        if [ ! -f "$tmp/plug.vim" ]; then
            mkdir -p "$tmp"
            tmpB="https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
            curl $tmpB > "$tmp/plug.vim"
        fi
    fi


    ## nvm
    if [ -n "`echo " 1 " | grep " $cmdPlatformCode "`" ]; then
        if [ ! -d "$ysUserdirPath/.nvm" ]; then
            [ -f "$HOME/.bashrc" ] && cp "$HOME/.bashrc" "$HOME/.bashrc.tmp"
            export NVM_DIR="$ysUserdirPath/.nvm"
            mkdir $NVM_DIR
            curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
            [ -f "$HOME/.bashrc.tmp" ] && mv "$HOME/.bashrc.tmp" "$HOME/.bashrc"
        fi
        if ! type node &> /dev/null || ! type npm &> /dev/null ; then
            source "$ysUserdirPath/.nvm/nvm.sh"
            export NVM_DIR="$ysUserdirPath/.nvm"
            nvm use --delete-prefix node &> /dev/null
            if [ $? -ne 0 ]; then
                nvm install --lts
                if ! type node &> /dev/null ; then
                    nvm use --delete-prefix node
                fi
            fi
        fi
    fi


    ## nodeApp
    if [ -n "`echo " 1 2 " | grep " $cmdPlatformCode "`" ]; then
        if ! type npm &> /dev/null ; then
            echo -e "\e[31m未安裝 nodeApp。 找不到 npm，請試圖安裝 node 或者 nvm。\e[00m"
        elif [ ! -f "$_libsh/nodeApp/package.json" ] ; then
            echo -e "\e[31m未安裝 nodeApp。 找不到 \"$_libsh/nodeApp/package.json\"。\e[00m"
        elif [ ! -d "$_libsh/nodeApp/node_modules" ]; then
            cd "$_libsh/nodeApp"
            npm install
            cd "$_libsh/nodeApp/alone-gitbook"
            npm install
            ln -s "$_libsh/nodeApp/alone-gitbook/node_modules/.bin/gitbook" \
                "$_libsh/nodeApp/node_modules/.bin"
            cd $_PWD

            ## gitbook
            if [ ! -d "$ysUserdirPath/.gitbook" ]; then
                if [ -d "$HOME/.gitbook" ]; then
                    mv "$HOME/.gitbook" "$ysUserdirPath"
                else
                    mkdir "$ysUserdirPath/.gitbook"
                fi
            fi
        fi
    fi
}
fnYsBash_installDefaultApp

