#!/bin/bash
# 一鍵完成用戶目錄


__dirname="`dirname $0`"


tmp=""
ysName=""
lsfileInfo=""
tmpPathName=""


rtnResolve_ParentDirectory=""
fnResolve_ParentDirectory() {
    local path="$1"

    while [ -n "`echo "$path" | grep \"/\.\.\B\"`" ]
    do
        path=`echo "$path" | sed "s/\/\([^\/]*\)\/\.\.//g"`
    done

    rtnResolve_ParentDirectory="$path"
}

rtnResolve=""
fnResolve() {
    local path="$1"

    path=`echo "$path" | sed "s/\/\{2,\}/\//g"`
    fnResolve_ParentDirectory "$path"
    path="$rtnResolve_ParentDirectory"
    path=`echo "$path" | sed "s/\/\.\//\//g"`
    path=`echo "$path" | sed "s/\/$//g"`

    rtnResolve="$path"
}


if [ -z "`echo $__dirname | grep '^/'`" ]
then
    if [ "$__dirname" == "." ]
    then
        __dirname=""
    else
        __dirname="`echo \"$__dirname\" | sed \"s/^\.\(\/\)//\"`"
    fi

    __dirname="$PWD/$__dirname"
fi

fnResolve "$__dirname"
__dirname="$rtnResolve"


## ys 目錄

ysName="`echo \"$__dirname\" | sed \"s/\/[^/]*$//\"`"

if [ ! -e "$HOME/ys" ] && [ ! -L "$HOME/ys" ]
then
    ln -s "$ysName" "$HOME/ys"
fi


## .ys 目錄

if [ ! -e "$HOME/.ys" ] && [ ! -L "$HOME/.ys" ]
then
    ln -s "$__dirname" "$HOME/.ys"
fi


## 安裝 vim-plug

tmpPathName="$__dirname/.vim/autoload"

if [ ! -d "$tmpPathName" ]
then
    mkdir -p "$tmpPathName"
    curl https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim > "$tmpPathName/plug.vim"
fi


## 鏈結文件

for tmpPathName in `ls -A $__dirname`
do
    if [ "$tmpPathName" == "autoFinish" ]; then continue; fi

    if [ -e "$HOME/$tmpPathName" ] || [ -L "$HOME/$tmpPathName" ]
    then
        if [ -d "$HOME/$tmpPathName" ]
        then
            lsfileInfo="`ls -FAl $HOME | grep \"$tmpPathName\/\"`"
        else
            lsfileInfo="`ls -Fl "$HOME/$tmpPathName"`"
        fi
        lsfileInfo="`echo $lsfileInfo | cut -d " " -f "1 9-" | sed "s/^\([^ ]*\)/\(\1\)/"`"
        printf "文件已存在： %s\n" "$lsfileInfo"
        printf "是否覆蓋文件 (Yes/No)： "
        read tmp

        case $tmp in
            [Yy] | "Yes" | "yes" )
                printf "cover  %s  with  %s\n\n" "\"$HOME/$tmpPathName\"" "\"$__dirname/$tmpPathName\""
                rm -rf "$HOME/$tmpPathName"
                ln -s "$HOME/.ys/$tmpPathName" $HOME
                ;;
            * )
                printf "Not copy  %s  to  %s\n\n" "\"$__dirname/$tmpPathName\"" "\"$HOME/$tmpPathName\""
                ;;
        esac
    else
        ln -s "$HOME/.ys/$tmpPathName" $HOME
    fi
done


## .bashrc 設定

if [ ! -f "$HOME/.bashrc" ] || [ -z "`grep \"\(## 自訂 ##\|ys\/\.bash_envtree\)\" \"$HOME/.bashrc\"`" ]
then
    if [ ! -f "$HOME/.bashrc" ]; then echo -e "# ~/.bashrc" > "$HOME/.bashrc"; fi
    echo -e "\n\n\n## 自訂 ##\n\nsource $HOME/ys/.bash_envtree\n" >> "$HOME/.bashrc"
fi

