#!/bin/bash
# 臺灣鏡像站


__filename=`realpath "$0"`
_dirsh=`dirname "$__filename"`


originMirrorlist=""
list='
Server = http://ftp.tku.edu.tw/Linux/ArchLinux/$repo/os/$arch
Server = https://shadow.ind.ntou.edu.tw/archlinux/$repo/os/$arch
Server = http://archlinux.cs.nctu.edu.tw/$repo/os/$arch
Server = https://ftp.yzu.edu.tw/Linux/archlinux/$repo/os/$arch
'

if [ ! -z "`cat /etc/pacman.d/mirrorlist | grep 'http://[^/]\+\.tw'`" ]; then
    originMirrorlist="`cat /etc/pacman.d/mirrorlist`"
    echo "$originMirrorlist$list" | "$_dirsh"/rankmirrors -n 4 - |
        sudo tee /etc/pacman.d/mirrorlist
fi

