#!/bin/bash
# 列出目錄內容


##shStyle 介面函式


fnLsFile__filename=`realpath "$0"`
fnLsFile_fileName=`basename "$fnLsFile__filename"`

fnLsFile() {
    local method="$1"
    local dirPath="$2"

    local tmp
    local redBFormatArgu
    local dirRealPath listTxt errTxt
    local parseName
    local opt_markQuery=0
    local addTxtFilePath="${fnLsFile__filename}.addTxt.tmp"
    local errMagFilePath="${fnLsFile__filename}.errMag.tmp"

    [ -t 1 ] \
        && redBFormatArgu="`tput setaf 1; tput bold`%s`tput sgr0`\n" \
        || redBFormatArgu="%s\n"

    case "$method" in
        FINDEXECOPT )
            if [ "$dirPath" == "." ]; then
                exit
            fi

            parseName=`fnLsList_markQuery "${dirPath:2}" "!"`
            if [[ "$parseName" =~ "!" ]]; then
                fnLsList_markQuery "$parseName" >> "$addTxtFilePath"
                echo "[$fnLsFile_fileName]: 子目錄路徑中包含特殊符號。" >> "$errMagFilePath"
                exit 1
            else
                echo "$parseName" >> "$addTxtFilePath"
            fi
            exit
            ;;
        markQuery )
            fnLsList_markQuery "$dirPath"
            exit
            ;;
        --markQuery )
            opt_markQuery=1
            shift
            method="$1"
            dirPath="$2"
            ;;
    esac

    dirPath="$method"
    dirRealPath=`realpath "$dirPath" 2> /dev/null`
    tmp=$?

    if [ $# -ne 1 ] || [ $tmp -ne 0 ]; then
        printf "$redBFormatArgu" "[$fnLsFile_fileName]: 不符合預期的參數。" >&2
        exit 1
    elif [ ! -d "$dirPath" ]; then
        printf "$redBFormatArgu" \
            "[$fnLsFile_fileName]:  \"$dirPath\" 路徑不符合目錄類型。" >&2
        exit 1
    elif [ $opt_markQuery -eq 0 ] \
        && [[ "`fnLsList_markQuery "$dirRealPath" "!"`" =~ "!" ]]
    then
        printf "$redBFormatArgu" "[$fnLsFile_fileName]: 絕對路徑中包含特殊符號。" >&2
        exit 1
    fi

    [ ! -e "$addTxtFilePath" ] || rm "$addTxtFilePath"
    [ ! -e "$errMagFilePath" ] || rm "$errMagFilePath"

    cd "$dirPath"
    find "." -maxdepth 1 -exec "$fnLsFile__filename" FINDEXECOPT {} \;

    if [ -f "$addTxtFilePath" ]; then
        listTxt="`cat "$addTxtFilePath"`"
        rm "$addTxtFilePath"
    fi
    if [ -f "$errMagFilePath" ]; then
        errTxt="`cat "$errMagFilePath" | uniq`"
        rm "$errMagFilePath"
    fi

    if [ -n "$errTxt" ] && [ $opt_markQuery -eq 0 ]; then
        printf "$redBFormatArgu" "$errTxt" >&2
        exit 1
    elif [ -n "$listTxt" ]; then
        echo "$listTxt"
    fi
}
fnLsList_markQuery() {
    local url="$1"
    local symbol="$2"

    [ -n "$symbol" ] || symbol="?"

    if [ -n "$url" ]; then
        # ?: ~ ! @ # $ ^ * ( ) { } [ ] | " ' < > \n
        echo -n "$url" | tr "~!@#$^*(){}[]|\"\'<>\n" "$symbol"
        echo
    fi
}


##shStyle ###


fnLsFile "$@"

