#!/bin/bash
# 指令集


case `uname` in
    *CYGWIN*) local cmdPlatform="Cygwin" ;;
    *) local cmdPlatform="Linux" ;;
esac


## 系統環境變數

local ys="${HOME}/ys"

case $cmdPlatform in
    "Cygwin")
        # 不明白 /cygdrive/c/ 與 C:/ 的差異
        # 但是 node 好像呼叫決對路徑會冠上 C:/

        local ProgramFile86="/cygdrive/c/Program Files (x86)"
        local UserProFile="/cygdrive/c/Users/bwaycer"
        export Cer="/cygdrive/c/Cer"
        ;;
    "Linux")
        export Cer="/mnt/hgfs/Cer"
        ;;
esac


## 應用程式

case $cmdPlatform in
    "Cygwin")
        alias open="cygstart" # explorer.exe 由微軟開發
        ;;
    "Linux")
        alias open="xdg-open"
        ;;
esac


## 移動指令

alias Bway.cd.Cer="cd $Cer"

case $cmdPlatform in
    "Cygwin")
        alias Bway.cd.ProgramFile86='cd $ProgramFile86'
        alias Bway.cd.User='cd $UserProFile'
        alias Bway.cd.Desktop='cd $UserProFile/Desktop'
        alias Bway.cd.Download='cd $UserProFile/Downloads'
        ;;
    "Linux")
        ;;
esac


## 殼層腳本

# 搜尋文件名稱
alias Bway.sh.search.name='~/ys/shell/search_name.sh'

# 搜尋文件內容
alias Bway.sh.search.content='~/ys/shell/search_content.sh'


## 連線

alias Bway.link.ptt='ssh bbsu@ptt.cc'

