#!/bin/bash
# 初始化 cygwin /usr/local/bin（執行檔）


printf "請允許常用檔案於 /usr/local/bin 資料夾內建立鏈結（按任意鍵繼續）:"
read

$(cygstart --action=runas sh ~/ys/myBash/cygwin_usrLocalBinInit $USER>/dev/null 2>&1)
exitCode=$?

if [ $exitCode -eq 0 ]; then
    echo " 查看資料夾 \`ls -al /usr/local/bin\`"
else
    echo -e "\e[1;31m 未成功執行，請再嘗試\e[0m"
fi

